### ISSUE TITLE
How could I disable ? ---> "Error: Could not resolve the remote domain....."

### ISSUE THREAD

**Issue by okcy1016** [DynamicTranslator/DynamicTranslator#34]
### Error: Could not resolve the remote domain
![default](https://user-images.githubusercontent.com/24411020/34677948-b1140c42-f4cc-11e7-8346-3777f98d2bb0.PNG)
The specified domain is "www.google-analytics.com";

And, my country (China) has blocked all of the google-things, but when I only checked the google translate in DynamicTranslator, what I highlight in browser **can** be translated (don't know why..), but it keeps showing the disturbing popup form (image is above).

I want to be informed if this error bezel could be disabled.

**Thanks for your hard work! ヾ(＾∇＾)**

**Comment by osoykan** [comment]
@okcy1016,

DynamicTranslator uses Google Analytics for gathering usage information to analyze country based usage since i can not remove analytics connection from it.
