### ISSUE TITLE
There's no Italian article

### ISSUE THREAD

**Issue by EmanueleS2** [DynamicTranslator/DynamicTranslator#37]
Hi! I'd like to say that what is written inside [https://github.com/DynamicTranslator/DynamicTranslator/blob/dev/README.md](url) is actually wrong. Your "Italian" article is in Spanish.

**Comment by osoykan** [comment]
Oops, my Spanish sounds like Italian that's why :) kidding, I must have been misplaced. I'd definetely need a re-write to this readme thing tho, thanks for pointing out!

**Comment by osoykan** [comment]
Oops, my Spanish sounds like Italian that's why :) kidding, I must have misplaced. I'd definetely need a re-write to this readme thing tho, thanks for pointing out!
