### ISSUE TITLE
Feature request: OCR implementation

### ISSUE THREAD

**Issue by cartals** [DynamicTranslator/DynamicTranslator#44]
I think, it would be more powerful when OCR added. Also it would very useful reading scanlations from jpg png.

**Comment by osoykan** [comment]
Hi, 

Thanks for the suggestion.

DynamicTranslator aims to translate only detectable text content; adding character recognition would increase the complexity as opposed to simplicity it has now.

**Comment by cartals** [comment]
Do you think adding Linux support as well?

**Comment by osoykan** [comment]
Yes, I was thinking about adding support for Linux and MacOSx, although these are entirely different beasts.

For the MacOSx part, I had done some investigation about how I can show notification in OSx could not find proper cross-platform notification library to interact with. 
Notifications on OSx that cross-platform frameworks provide are limited like this:

![image](https://user-images.githubusercontent.com/9823085/82497166-1ac16f80-9aee-11ea-84fa-03015bf9df49.png)
Hence, I need to implement DynamicTranslator in swift to get %100 control of OSx native UI, I guess. So, there are some points I need to investigate, or if someone opens a PR and creates a spike on this topic would be great.

The same applies to Linux, needs some investigation.
