### ISSUE TITLE
[TR] About System Resource Usage

### ISSUE THREAD

**Issue by toprak** [DynamicTranslator/DynamicTranslator#45]
Merhaba abi, ben bu uygulamayı senin kullandığın şekilde yani pot player ve bunu beraber kullanıyorum ama bu program cpu'mun içinden geçiyor adeta, bunu düzeltmenin bir yolu var mı?

**Comment by toprak** [comment]
Sorun şu ki, örnek veriyorum bu anlamlar çıkıyor ya abi, onları kapatırken cpu kullanımı 95 vs. oluyor ama şuan sıkıntı yok kendisinin kapanmasını beklemem gerek sanırım.

**Comment by osoykan** [comment]
Selam @toprak,

DynamicTranslator'u ben kullanmayali uzun zaman oldu ama, CPU yukseltme durumlarini hatirliyorum. Genelde kullanicilarin da bahsettigi bir durum. Burada( #42) yeniden yazmaya baslamistim DT'yi, CPU kullanan ve gereksiz is yapan noktalarini sildim orada, daha yalin ve kaynaklari iyi kullanan bir uygulama olacak. Calismayan yerleri var halen gelistirme asamasinda ama, kodu alip derleyip `.exe` dosyasini alip deneyebilirsen kaynak tuketimine bakabilirsin, halen bir problem varsa orda duzeltme yapariz.

**Comment by toprak** [comment]
Abi, pek anlamam derleme işlerinden ama VSCODE ile cloneladım ondan sonra DT'nin solution dosyasını açtım vscode ile ve build dedim, wpf exe verdi, aynı abi maalesef ayrıca pot playerda durdurduğumuzda videoyu altyazıdan kelimeler seçebiliyoruz sanki önceden oraları görebiliyordu dt şuan o da olmuyor gibi :)

**Comment by osoykan** [comment]
Dogru yapmissin, fakat uygulama henuz dogru calismiyor o zaman:) Bu soruna da bakicam o zaman o PR icerisinda.

**Comment by toprak** [comment]
Kolay gelsin abi :)

**Comment by toprak** [comment]
Abi bir gelişme var mı :D

**Comment by osoykan** [comment]
Olucak biseler:)

**Comment by osoykan** [comment]
Yeni pre-release version yayinladim, bi bakabilirsen calismayan biseler var mi bilinenlerin disinda. Hata felan cikarsa issue acabilirsin.

https://github.com/DynamicTranslator/DynamicTranslator/releases/download/5.0.0-pre1/5.0.0-pre1.zip

**Comment by toprak** [comment]
çalışıyor :)

**Comment by toprak** [comment]
@osoykan abi how to use videondaki gibi pot playerda kullanamıyorum sen ne yapıyordun shift ile birden fazla kelimeyi seçiyorsun ondan sonra mouse ile tıklıyor musun yoksa pot playerda bir ayar mı yaptın?

**Comment by toprak** [comment]
Cannot acess a dispossed object obhect name socketshttphandler error alıyorum
