### ISSUE TITLE
[TR] Cannot acess a dispossed object

### ISSUE THREAD

**Issue by toprak** [DynamicTranslator/DynamicTranslator#46]
Cannot acess a dispossed object object name sockets httphandler error alıyorum abi, bir de senin bu nasıl kullanılır videonda pot player video oynatıcısında da kullanabiliyorsun dynamic'i ben beceremedim potplayere özel bir ayar mı çektin?

**Comment by osoykan** [comment]
Pot playeri kullanmayalı baya uzun zaman oldu artık Windows kullanmadığım için normal zamanda. Yani, o özellik gitmiş olabilir, çünkü yaptığım değişikliklerle kopyala-yapıştır/pano’yu dinlemeyi bırakmıştım daha efektif çalışması açısından. Mouse’i sürüklersen metin üzerinde basılıyken ancak öyle yanıt veriyor şimdi. 

Diğer konu ise, nerde alıyorsun bildirim olarak sağda üstte mi çıkıyor çeviri gibi? Hangi esnada oluyor?

**Comment by toprak** [comment]
Kelime seçtikten sonra o kelimelerin anlamının çıktığı yerde çıkıyor da çok sık da olmuyor 2 kere falan oldu kapatıp açınca düzeliyor.

**Comment by osoykan** [comment]
Anladim, bakicam zaman buldugumda, tesekkurler bildirdigin icin.
