### ISSUE TITLE
When starting translator, default copy paste keys not working

### ISSUE THREAD

**Issue by onurcanyilmaz** [DynamicTranslator/DynamicTranslator#47]
**DynamicTranslator Version : 3.5.0**

I use Windows 10 OS

There is a problem as I mentioned in the title, default copy paste keys not working.
When i closing translator, copy paste keys  working.

I haven't checked the source code yet
Do you have any idea?

**Comment by osoykan** [comment]
Yes, this is expected behavior.  The only way of getting a text from the windows you're on, and you have selected, is that after selecting it by mouse move(double-click, drag-drop), DynamicTranslator sends a `CTRL+C` to capture the text.

**Comment by onurcanyilmaz** [comment]
Thanks.
